language: node_js
node_js:
 - lts/*

cache:
 npm: true
 directories:
  - node_modules
  - ~/.cache

branches:
 only:
  - main

install:
 - npm install

script:
 - npm run build:gh:pages

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: main

notifications:
  webhooks: https://www.travisbuddy.com
